### ISSUE TITLE
PyBombs throws sudo parse error when trying to build image

### ISSUE THREAD

**Issue by robisen1** [radioML/dockerRML#3]
PyBOMBS - INFO - PyBOMBS Version 2.2.0
PyBOMBS.install_manager - INFO - Phase 1: Creating install tree and installing binary packages:
>>>/etc/sudoers.d/x2go: syntax error near line 1 <<<
sudo: parse error in  near line 1
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin

**Comment by yonidavidson** [comment]
Hi, Which Dockerfile is the problem ?
In general - using sudo in dockerfile is not needed since you have the USER key to change users inside.


Does the error happen when you try building locally on host or using an automated build like dockerhub?
